#!/usr/bin/env bash
# Flash ESPHome firmware with automatic version bumping and upload verification.
#
# Usage:
#   ./scripts/flash.sh                        # auto-detect device
#   ./scripts/flash.sh device-ili9341.yaml    # different config
#   USB=1 ./scripts/flash.sh                  # force USB (needs cable)
#   DEVICE_IP=192.168.1.42 ./scripts/flash.sh # explicit IP for OTA
#   SKIP_VERIFY=1 ./scripts/flash.sh          # skip version check after flash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$SCRIPT_DIR/.."
CONFIG="${1:-device.yaml}"
DEVICE_IP="${DEVICE_IP:-10.100.102.46}"
TIMEOUT=4

VERSION_FILE="$ROOT_DIR/version.txt"
FAIL_FILE="$ROOT_DIR/upload_failures.txt"
HEADER="$ROOT_DIR/custom/version_info.h"

if ! command -v esphome &>/dev/null; then
  echo "✗  esphome not found.  pip install esphome"
  exit 1
fi

cd "$ROOT_DIR"

# ── Bump version ──────────────────────────────────────────────────────────────
OLD_VERSION=$(cat "$VERSION_FILE" 2>/dev/null || echo "0")
NEW_VERSION=$((OLD_VERSION + 1))
echo "$NEW_VERSION" > "$VERSION_FILE"
echo "▶  Firmware version: v$NEW_VERSION (was v$OLD_VERSION)"

# ── Generate version header ───────────────────────────────────────────────────
cat > "$HEADER" << HEADER_EOF
#pragma once
// Auto-generated by scripts/flash.sh — do not edit manually.
// Run ./scripts/flash.sh to bump version and flash.
#define FW_VERSION_NUM $NEW_VERSION
#define FW_VERSION_STR "v$NEW_VERSION"
HEADER_EOF

# Touch the header to force PlatformIO to recompile main.cpp.o
touch "$HEADER"

# ── Compile ───────────────────────────────────────────────────────────────────
echo "▶  Compiling $CONFIG (v$NEW_VERSION)..."
esphome compile "$CONFIG"

# ── Determine upload method ───────────────────────────────────────────────────
use_ota() {
  ping -c 1 -W "$TIMEOUT" "$DEVICE_IP" &>/dev/null
}

upload_firmware() {
  local target="$1"
  esphome upload "$CONFIG" --device "$target"
}

if [ "${USB:-0}" = "1" ]; then
  echo "▶  USB forced — flashing via serial..."
  fuser -k /dev/ttyUSB0 2>/dev/null || true
  upload_firmware /dev/ttyUSB0
  UPLOAD_METHOD="USB"
elif use_ota; then
  echo "▶  Device reachable at ${DEVICE_IP} — flashing OTA..."
  upload_firmware "$DEVICE_IP"
  UPLOAD_METHOD="OTA"
elif [ -e /dev/ttyUSB0 ]; then
  echo "▶  Device offline, USB found — flashing via serial..."
  fuser -k /dev/ttyUSB0 2>/dev/null || true
  upload_firmware /dev/ttyUSB0
  UPLOAD_METHOD="USB"
else
  echo "✗  Device not reachable at ${DEVICE_IP} and no USB found."
  echo "   Connect USB cable or check device is on WiFi."
  echo "   Try: DEVICE_IP=<actual-ip> ./scripts/flash.sh"
  # Rollback version since we couldn't upload
  echo "$OLD_VERSION" > "$VERSION_FILE"
  exit 1
fi

echo "✔  Upload complete (${UPLOAD_METHOD})"

# ── Version verification ──────────────────────────────────────────────────────
if [ "${SKIP_VERIFY:-0}" = "1" ] || [ "$UPLOAD_METHOD" = "USB" ]; then
  echo "▶  Skipping version verification (USB or SKIP_VERIFY set)"
  exit 0
fi

echo "▶  Waiting 12s for device reboot..."
sleep 12

echo "▶  Collecting device logs to verify version v$NEW_VERSION..."
LOGS=$(timeout 35 esphome logs "$CONFIG" --device "$DEVICE_IP" 2>&1 || true)

DEVICE_VERSION=$(echo "$LOGS" | grep -oE 'FIRMWARE VERSION: v[0-9]+' | grep -oE '[0-9]+$' | tail -1)

FAILS=$(cat "$FAIL_FILE" 2>/dev/null || echo "0")

if [ -z "$DEVICE_VERSION" ]; then
  echo "⚠️  WARNING: Could not read version from device logs."
  echo "   Expected: v$NEW_VERSION"
  echo "   The device may still be booting — check logs manually."
  NEW_FAILS=$((FAILS + 1))
  echo "$NEW_FAILS" > "$FAIL_FILE"
  echo "   Upload failure count: $NEW_FAILS (total)"

elif [ "$DEVICE_VERSION" -lt "$NEW_VERSION" ]; then
  echo "❌ CACHED BUILD: device=v$DEVICE_VERSION expected=v$NEW_VERSION"
  NEW_FAILS=$((FAILS + 1))
  echo "$NEW_FAILS" > "$FAIL_FILE"
  echo "   Upload failure count: $NEW_FAILS (total)"
  echo "▶  Forcing clean rebuild and re-upload..."
  # Clean PlatformIO build cache for this project
  rm -f "$ROOT_DIR/.esphome/build/esp32-display/.pioenvs/esp32-display/src/main.cpp.o" 2>/dev/null || true
  touch "$HEADER"
  esphome compile "$CONFIG"
  upload_firmware "$DEVICE_IP"
  echo "✔  Re-upload complete — recheck logs manually to verify v$NEW_VERSION"

elif [ "$DEVICE_VERSION" -gt "$NEW_VERSION" ]; then
  echo "⚠️  Device reports v$DEVICE_VERSION > local v$NEW_VERSION"
  echo "   Syncing local version file to v$DEVICE_VERSION"
  echo "$DEVICE_VERSION" > "$VERSION_FILE"

else
  echo "✅ Version confirmed: v$NEW_VERSION running on device"
  echo "   Upload failures to date: $FAILS"
fi
